In [1]:
import pandas as pd
import numpy as np

pd.set_option('display.max_columns', None)

In [2]:
clientes_2012 = pd.read_excel("C:/Users/glria/Documents/Análisis_datos/Proyectos/Proyecto4_Gloria/EDA_Python_GloriaMartin/Archivos/customer-details.xlsx", sheet_name=0)
clientes_2012.head()

,Unnamed: 0,Income,Kidhome,Teenhome,Dt_Customer,NumWebVisitsMonth,ID
0,0,161770,1,0,2012-04-04,29,089b39d8-e4d0-461b-87d4-814d71e0e079
1,1,85477,1,1,2012-12-30,7,e9d37224-cb6f-4942-98d7-46672963d097
2,2,147233,1,1,2012-02-02,5,3f9f49b5-e410-4948-bf6e-f9244f04918b
3,3,121393,1,2,2012-12-21,29,9991fafb-4447-451a-8be2-b0df6098d13e
4,4,63164,1,2,2012-06-20,20,eca60b76-70b6-4077-80ba-bc52e8ebb0eb

In [3]:
clientes_2012.info()

<class 'pandas.DataFrame'>
RangeIndex: 20115 entries, 0 to 20114
Data columns (total 7 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Unnamed: 0         20115 non-null  int64
 1   Income             20115 non-null  int64
 2   Kidhome            20115 non-null  int64
 3   Teenhome           20115 non-null  int64
 4   Dt_Customer        20115 non-null  datetime64[us]
 5   NumWebVisitsMonth  20115 non-null  int64
 6   ID                 20115 non-null  str
dtypes: datetime64[us](1), int64(5), str(1)
memory usage: 1.1 MB

In [4]:
clientes_2013 = pd.read_excel("C:/Users/glria/Documents/Análisis_datos/Proyectos/Proyecto4_Gloria/EDA_Python_GloriaMartin/Archivos/customer-details.xlsx", sheet_name=1)
clientes_2013.head()

,Unnamed: 0,Income,Kidhome,Teenhome,Dt_Customer,NumWebVisitsMonth,ID
0,0,82407,0,1,2013-10-07,29,ef81336c-e41a-46d0-8a30-5d4ac3b836be
1,1,24877,0,0,2013-04-21,32,50b224ac-84b4-42a7-aba9-3e1d1d620479
2,2,78839,1,0,2013-11-25,21,9cb15c53-b647-464a-add9-09cdae04897c
3,3,113859,1,1,2013-01-06,12,f8aaf334-949d-4943-a214-b64fe9c088b4
4,4,147317,0,0,2013-07-10,14,885fe85a-3718-4760-a32a-a57628cf7528

In [5]:
clientes_2013.info()

<class 'pandas.DataFrame'>
RangeIndex: 8965 entries, 0 to 8964
Data columns (total 7 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Unnamed: 0         8965 non-null   int64
 1   Income             8965 non-null   int64
 2   Kidhome            8965 non-null   int64
 3   Teenhome           8965 non-null   int64
 4   Dt_Customer        8965 non-null   datetime64[us]
 5   NumWebVisitsMonth  8965 non-null   int64
 6   ID                 8965 non-null   str
dtypes: datetime64[us](1), int64(5), str(1)
memory usage: 490.4 KB

In [6]:
clientes_2014 = pd.read_excel("C:/Users/glria/Documents/Análisis_datos/Proyectos/Proyecto4_Gloria/EDA_Python_GloriaMartin/Archivos/customer-details.xlsx", sheet_name=2)
clientes_2014.head()

,Unnamed: 0,Income,Kidhome,Teenhome,Dt_Customer,NumWebVisitsMonth,ID
0,0,168812,1,1,2014-06-10,27,4d6c811c-0f24-4a73-b374-2ebd1f80d46e
1,1,108615,2,1,2014-04-05,24,eef0f24f-cbdb-4c67-b371-09d7bc59695e
2,2,179041,0,2,2014-09-22,4,bbfdcedd-199d-4927-94bb-5dad051ff471
3,3,116639,2,2,2014-08-16,3,e8ebb67d-4ee1-4615-b701-eefe3af607eb
4,4,49537,0,1,2014-09-05,28,f7f79ace-0024-4505-a401-f340946f0942

In [7]:
clientes_2014.info()

<class 'pandas.DataFrame'>
RangeIndex: 14090 entries, 0 to 14089
Data columns (total 7 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Unnamed: 0         14090 non-null  int64
 1   Income             14090 non-null  int64
 2   Kidhome            14090 non-null  int64
 3   Teenhome           14090 non-null  int64
 4   Dt_Customer        14090 non-null  datetime64[us]
 5   NumWebVisitsMonth  14090 non-null  int64
 6   ID                 14090 non-null  str
dtypes: datetime64[us](1), int64(5), str(1)
memory usage: 770.7 KB